Dev
KubaKlin/Async-pt.2 pull request #1
Opened 2024-12-10 20:05 UTC by KubaKlin

2024-12-12 21:50 UTC, mwanago commented
You didn't include the `package-lock.json` file

2024-12-12 22:12 UTC, mwanago requested changes

2024-12-12 22:12 UTC, mwanago commented on src/index.js
> +import { wait } from './components/wait';
I wouldn't use the word `components` here - it could be confused with React components that we will create soon. I would suggest `utilities`.

2024-12-12 22:12 UTC, mwanago commented on src/index.js
> +  button.innerText = images.indexOf(image) + 1;
Change
```
images.forEach(function (image) {
```
to
```
images.forEach(function (image, index) {
```
to avoid doing `indexOf`

2024-12-12 22:12 UTC, mwanago commented on src/index.js
> +          });
You are doing `wait(700)` twice which does not make much sense. You could simplify it to
```javascript
wait(700).then(function () {
  currentImage.remove();
  imageWrapper.append(image);
});
```

2024-12-12 22:12 UTC, mwanago commented on src/index.js
> +          });
We can simplify it even more with chaining
by first waiting for 700 milliseconds and then waiting for 10 more milliseconds
```javascript
getImageElementWhenLoaded(selectedImage, imageWrapper)
  .then(function (image) {
    const currentImage = imageWrapper.querySelector('img');

    if (currentImage) {
      currentImage.classList.remove('loaded');
      wait(700)
        .then(function () {
          currentImage.remove();
          imageWrapper.append(image);
          return wait(10);
        })
        .then(function() {
          image.classList.add('loaded');
        })
    } else {
      imageWrapper.append(image);
      wait(10).then(function () {
        image.classList.add('loaded');
      });
    }
    informationParagraph.innerText = '';
  })
  .catch(function () {
    informationParagraph.innerText = 'loading error';
  });
```

2024-12-12 22:12 UTC, mwanago commented on src/index.js
> +          });
We could simplify it further by changing the order of if statements and using `return`

```javascript
getImageElementWhenLoaded(selectedImage, imageWrapper)
  .then(function (image) {
    const currentImage = imageWrapper.querySelector('img');
    informationParagraph.innerText = '';

    if (!currentImage) {
      imageWrapper.append(image);
      return wait(10)
        .then(function () {
          image.classList.add('loaded');
        });
    }

    currentImage.classList.remove('loaded');
    return wait(700)
      .then(function () {
        currentImage.remove();
        imageWrapper.append(image);
        return wait(10);
      })
      .then(function() {
        image.classList.add('loaded');
      })
  })
  .catch(function () {
    informationParagraph.innerText = 'loading error';
  });
```

2024-12-13 09:04 UTC, KubaKlin commented on src/index.js
> +import { wait } from './components/wait';
ok - changed

2024-12-13 09:09 UTC, KubaKlin commented on src/index.js
> +          });
ok, thats better - changed

2024-12-16 00:03 UTC, mwanago approved these changes

2025-10-24 06:52 UTC, merged